version: "3.8"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=articlesDB
      - POSTGRES_USER=janire
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U janire"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8088:8080"
    networks:
      - app-network

  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app/backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://janire:password@database:5432/articlesDB
    restart: always
    networks:
      - app-network

  web:
    container_name: web
    image: nginx:latest
    ports:
      - "8005:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apk:/usr/share/nginx/html/apk
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
