basePath: /
host: localhost:8080
info:
  contact: {}
  description: API for managing articles
  title: Article REST API
  version: "1.0"
paths:
  /:
    get:
      description: Welcome message for the Article REST API
      produces:
      - text/plain
      responses:
        "200":
          description: Welcome to the Article REST API!
          schema:
            type: string
      summary: Home page
swagger: "2.0"
